elementos = {
    'H': {'numero_atomico': 1, 'nome': 'Hidrogênio', 'massa_atomica': 1.008},
    'He': {'numero_atomico': 2, 'nome': 'Hélio', 'massa_atomica': 4.003},
    'Li': {'numero_atomico': 3, 'nome': 'Lítio', 'massa_atomica': 6.941},
    'Be': {'numero_atomico': 4, 'nome': 'Berílio', 'massa_atomica': 9.012},
    'B': {'numero_atomico': 5, 'nome': 'Boro', 'massa_atomica': 10.811},
    'C': {'numero_atomico': 6, 'nome': 'Carbono', 'massa_atomica': 12.011},
    'N': {'numero_atomico': 7, 'nome': 'Nitrogênio', 'massa_atomica': 14.007},
    'O': {'numero_atomico': 8, 'nome': 'Oxigênio', 'massa_atomica': 15.999},
    'F': {'numero_atomico': 9, 'nome': 'Flúor', 'massa_atomica': 18.998},
    'Ne': {'numero_atomico': 10, 'nome': 'Neônio', 'massa_atomica': 20.18},
    'Na': {'numero_atomico': 11, 'nome': 'Sódio', 'massa_atomica': 22.99},
    'Mg': {'numero_atomico': 12, 'nome': 'Magnésio', 'massa_atomica': 24.305},
    'Al': {'numero_atomico': 13, 'nome': 'Alumínio', 'massa_atomica': 26.982},
    'Si': {'numero_atomico': 14, 'nome': 'Silício', 'massa_atomica': 28.086},
    'P': {'numero_atomico': 15, 'nome': 'Fósforo', 'massa_atomica': 30.974},
    'S': {'numero_atomico': 16, 'nome': 'Enxofre', 'massa_atomica': 32.065},
    'Cl': {'numero_atomico': 17, 'nome': 'Cloro', 'massa_atomica': 35.453},
    'Ar': {'numero_atomico': 18, 'nome': 'Argônio', 'massa_atomica': 39.948},
    'K': {'numero_atomico': 19, 'nome': 'Potássio', 'massa_atomica': 39.098},
    'Ca': {'numero_atomico': 20, 'nome': 'Cálcio', 'massa_atomica': 40.078},
    'Sc': {'numero_atomico': 21, 'nome': 'Escândio', 'massa_atomica': 44.956},
    'Ti': {'numero_atomico': 22, 'nome': 'Titânio', 'massa_atomica': 47.867},
    'V': {'numero_atomico': 23, 'nome': 'Vanádio', 'massa_atomica': 50.942},
    'Cr': {'numero_atomico': 24, 'nome': 'Cromo', 'massa_atomica': 51.996},
    'Mn': {'numero_atomico': 25, 'nome': 'Manganês', 'massa_atomica': 54.938},
    'Fe': {'numero_atomico': 26, 'nome': 'Ferro', 'massa_atomica': 55.845},
    'Co': {'numero_atomico': 27, 'nome': 'Cobalto', 'massa_atomica': 58.933},
    'Ni': {'numero_atomico': 28, 'nome': 'Níquel', 'massa_atomica': 58.693},
    'Cu': {'numero_atomico': 29, 'nome': 'Cobre', 'massa_atomica': 63.546},
    'Zn': {'numero_atomico': 30, 'nome': 'Zinco', 'massa_atomica': 65.38},
    'Ga': {'numero_atomico': 31, 'nome': 'Gálio', 'massa_atomica': 69.723},
    'Ge': {'numero_atomico': 32, 'nome': 'Germânio', 'massa_atomica': 72.63},
    'As': {'numero_atomico': 33, 'nome': 'Arsênio', 'massa_atomica': 74.922},
    'Se': {'numero_atomico': 34, 'nome': 'Selênio', 'massa_atomica': 78.971},
    'Br': {'numero_atomico': 35, 'nome': 'Bromo', 'massa_atomica': 79.904},
    'Kr': {'numero_atomico': 36, 'nome': 'Criptônio', 'massa_atomica': 83.798},
    'Rb': {'numero_atomico': 37, 'nome': 'Rubídio', 'massa_atomica': 85.468},
    'Sr': {'numero_atomico': 38, 'nome': 'Estrôncio', 'massa_atomica': 87.62},
    'Y': {'numero_atomico': 39, 'nome': 'Ítrio', 'massa_atomica': 88.906},
    'Zr': {'numero_atomico': 40, 'nome': 'Zircônio', 'massa_atomica': 91.224},
    'Nb': {'numero_atomico': 41, 'nome': 'Nióbio', 'massa_atomica': 92.906},
    'Mo': {'numero_atomico': 42, 'nome': 'Molibdênio', 'massa_atomica': 95.95},
    'Tc': {'numero_atomico': 43, 'nome': 'Tecnécio', 'massa_atomica': 98},
    'Ru': {'numero_atomico': 44, 'nome': 'Rutênio', 'massa_atomica': 101.07},
    'Rh': {'numero_atomico': 45, 'nome': 'Ródio', 'massa_atomica': 102.91},
    'Pd': {'numero_atomico': 46, 'nome': 'Paládio', 'massa_atomica': 106.42},
    'Ag': {'numero_atomico': 47, 'nome': 'Prata', 'massa_atomica': 107.87},
    'Cd': {'numero_atomico': 48, 'nome': 'Cádmio', 'massa_atomica': 112.41},
    'In': {'numero_atomico': 49, 'nome': 'Índio', 'massa_atomica': 114.82},
    'Sn': {'numero_atomico': 50, 'nome': 'Estanho', 'massa_atomica': 118.71},
    'Sb': {'numero_atomico': 51, 'nome': 'Antimônio', 'massa_atomica': 121.76},
    'Te': {'numero_atomico': 52, 'nome': 'Telúrio', 'massa_atomica': 127.6},
    'I': {'numero_atomico': 53, 'nome': 'Iodo', 'massa_atomica': 126.9},
    'Xe': {'numero_atomico': 54, 'nome': 'Xenônio', 'massa_atomica': 131.29},
    'Cs': {'numero_atomico': 55, 'nome': 'Césio', 'massa_atomica': 132.91},
    'Ba': {'numero_atomico': 56, 'nome': 'Bário', 'massa_atomica': 137.33},
    'La': {'numero_atomico': 57, 'nome': 'Lantânio', 'massa_atomica': 138.91},
    'Ce': {'numero_atomico': 58, 'nome': 'Cério', 'massa_atomica': 140.12},
    'Pr': {'numero_atomico': 59, 'nome': 'Praseodímio', 'massa_atomica': 140.91},
    'Nd': {'numero_atomico': 60, 'nome': 'Neodímio', 'massa_atomica': 144.24},
    'Pm': {'numero_atomico': 61, 'nome': 'Promécio', 'massa_atomica': 145},
    'Sm': {'numero_atomico': 62, 'nome': 'Samário', 'massa_atomica': 150.36},
    'Eu': {'numero_atomico': 63, 'nome': 'Európio', 'massa_atomica': 151.96},
    'Gd': {'numero_atomico': 64, 'nome': 'Gadolínio', 'massa_atomica': 157.25},
    'Tb': {'numero_atomico': 65, 'nome': 'Térbio', 'massa_atomica': 158.93},
    'Dy': {'numero_atomico': 66, 'nome': 'Disprósio', 'massa_atomica': 162.5},
    'Ho': {'numero_atomico': 67, 'nome': 'Hólmio', 'massa_atomica': 164.93},
    'Er': {'numero_atomico': 68, 'nome': 'Érbio', 'massa_atomica': 167.26},
    'Tm': {'numero_atomico': 69, 'nome': 'Túlio', 'massa_atomica': 168.93},
    'Yb': {'numero_atomico': 70, 'nome': 'Itérbio', 'massa_atomica': 173.05},
    'Lu': {'numero_atomico': 71, 'nome': 'Lutécio', 'massa_atomica': 174.97},
    'Hf': {'numero_atomico': 72, 'nome': 'Háfnio', 'massa_atomica': 178.49},
    'Ta': {'numero_atomico': 73, 'nome': 'Tântalo', 'massa_atomica': 180.95},
    'W': {'numero_atomico': 74, 'nome': 'Tungstênio', 'massa_atomica': 183.84},
    'Re': {'numero_atomico': 75, 'nome': 'Rênio', 'massa_atomica': 186.21},
    'Os': {'numero_atomico': 76, 'nome': 'Ósmio', 'massa_atomica': 190.23},
    'Ir': {'numero_atomico': 77, 'nome': 'Irídio', 'massa_atomica': 192.22},
    'Pt': {'numero_atomico': 78, 'nome': 'Platina', 'massa_atomica': 195.08},
    'Au': {'numero_atomico': 79, 'nome': 'Ouro', 'massa_atomica': 196.97},
    'Hg': {'numero_atomico': 80, 'nome': 'Mercúrio', 'massa_atomica': 200.59},
    'Tl': {'numero_atomico': 81, 'nome': 'Tálio', 'massa_atomica': 204.38},
    'Pb': {'numero_atomico': 82, 'nome': 'Chumbo', 'massa_atomica': 207.2},
    'Bi': {'numero_atomico': 83, 'nome': 'Bismuto', 'massa_atomica': 208.98},
    'Po': {'numero_atomico': 84, 'nome': 'Polônio', 'massa_atomica': 209},
    'At': {'numero_atomico': 85, 'nome': 'Astato', 'massa_atomica': 210},
    'Rn': {'numero_atomico': 86, 'nome': 'Radônio', 'massa_atomica': 222},
    'Fr': {'numero_atomico': 87, 'nome': 'Frâncio', 'massa_atomica': 223},
    'Ra': {'numero_atomico': 88, 'nome': 'Rádio', 'massa_atomica': 226},
    'Ac': {'numero_atomico': 89, 'nome': 'Actínio', 'massa_atomica': 227},
    'Th': {'numero_atomico': 90, 'nome': 'Tório', 'massa_atomica': 232.04},
    'Pa': {'numero_atomico': 91, 'nome': 'Protactínio', 'massa_atomica': 231.04},
    'U': {'numero_atomico': 92, 'nome': 'Urânio', 'massa_atomica': 238.03},
    'Np': {'numero_atomico': 93, 'nome': 'Neptúnio', 'massa_atomica': 237},
    'Pu': {'numero_atomico': 94, 'nome': 'Plutônio', 'massa_atomica': 244},
    'Am': {'numero_atomico': 95, 'nome': 'Amerício', 'massa_atomica': 243},
    'Cm': {'numero_atomico': 96, 'nome': 'Cúrio', 'massa_atomica': 247},
    'Bk': {'numero_atomico': 97, 'nome': 'Berquélio', 'massa_atomica': 247},
    'Cf': {'numero_atomico': 98, 'nome': 'Califórnio', 'massa_atomica': 251},
    'Es': {'numero_atomico': 99, 'nome': 'Einstênio', 'massa_atomica': 252},
    'Fm': {'numero_atomico': 100, 'nome': 'Férmio', 'massa_atomica': 257},
    'Md': {'numero_atomico': 101, 'nome': 'Mendelévio', 'massa_atomica': 258},
    'No': {'numero_atomico': 102, 'nome': 'Nobélio', 'massa_atomica': 259},
    'Lr': {'numero_atomico': 103, 'nome': 'Laurêncio', 'massa_atomica': 266},
    'Rf': {'numero_atomico': 104, 'nome': 'Rutherfórdio', 'massa_atomica': 267},
    'Db': {'numero_atomico': 105, 'nome': 'Dúbnio', 'massa_atomica': 268},
    'Sg': {'numero_atomico': 106, 'nome': 'Seabórgio', 'massa_atomica': 269},
    'Bh': {'numero_atomico': 107, 'nome': 'Bóhrio', 'massa_atomica': 270},
    'Hs': {'numero_atomico': 108, 'nome': 'Hássio', 'massa_atomica': 277},
    'Mt': {'numero_atomico': 109, 'nome': 'Meitnério', 'massa_atomica': 278},
    'Ds': {'numero_atomico': 110, 'nome': 'Darmstádio', 'massa_atomica': 281},
    'Rg': {'numero_atomico': 111, 'nome': 'Roentgênio', 'massa_atomica': 282},
    'Cn': {'numero_atomico': 112, 'nome': 'Copernício', 'massa_atomica': 285},
    'Nh': {'numero_atomico': 113, 'nome': 'Nihônio', 'massa_atomica': 286},
    'Fl': {'numero_atomico': 114, 'nome': 'Fleróvio', 'massa_atomica': 289},
    'Mc': {'numero_atomico': 115, 'nome': 'Moscóvio', 'massa_atomica': 290},
    'Lv': {'numero_atomico': 116, 'nome': 'Livermório', 'massa_atomica': 293},
    'Ts': {'numero_atomico': 117, 'nome': 'Tenessino', 'massa_atomica': 294},
    'Og': {'numero_atomico': 118, 'nome': 'Ogânio', 'massa_atomica': 294},

}

while True:
    sigla = input("Digite a sigla do elemento químico: ").capitalize()
    if sigla in elementos:
        elemento = elementos[sigla]
        print(f"Elemento: {elemento['nome']}")
        print(f"Número Atômico: {elemento['numero_atomico']}")
        print(f"Massa Atômica: {elemento['massa_atomica']}")
    elif sigla == "Sair":
        print('Você está saindo do sistema')
        break
    else:
        print("Elemento não encontrado.")